Add failing unit test for mode attribute dropping
apache/sling-org-apache-sling-feature-cpconverter pull request #97
Opened 2021-07-28 10:32 UTC by niekraaijmakers

Currently the mode attribute on the filter root get's dropped by the CPConverter.

To make sure this regression never occurs again in the future, we are adding this failing unit test.

2021-07-30 11:59 UTC, anchela requested changes
hi @niekraaijmakers , you need to have a SLING jira ticket for this. all modifications (maybe except for trivial typos) must be backed by ticket..... otherwise the release information is not accurate.

2021-07-30 12:07 UTC, anchela requested changes

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
> +                            Arrays.asList("org.apache.felix:org.apache.felix.framework:6.0.1"),
changing from Collections.singletonList to Arrays.asList seems to be an unrelated change. please revert if it is not required for the test to pass

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
> +                            Arrays.asList("org.apache.sling.commons.log.LogManager.factory.config~asd-retail"),
changing from Collections.singletonList to Arrays.asList seems to be an unrelated change. please revert if it is not required for the test to pass

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
> +                            Arrays.asList("org.apache.felix:org.apache.felix.framework:6.0.1"),
changing from Collections.singletonList to Arrays.asList seems to be an unrelated change. please revert if it is not required for the test to pass

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
> +                            Arrays.asList("org.apache.sling.commons.log.LogManager.factory.config~asd-retail"),
changing from Collections.singletonList to Arrays.asList seems to be an unrelated change. please revert if it is not required for the test to pass

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
> +                            Arrays.asList("org.apache.felix:org.apache.felix.framework:6.0.1"),
changing from Collections.singletonList to Arrays.asList seems to be an unrelated change. please revert if it is not required for the test to pass

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
> +                            Arrays.asList("org.apache.sling.commons.log.LogManager.factory.config~asd-retail"),
changing from Collections.singletonList to Arrays.asList seems to be an unrelated change. please revert if it is not required for the test to pass

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +        this.handlersManager = new DefaultEntryHandlersManager(Collections.emptyMap(), false,
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +     * "demo-cp3.zip" contains the same content as "demo-cp.zip" but with altered order leading to ACE being read before
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +     * This test would fail if user/group information was not collected during the first pass (i.e. corresponding
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +     *
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-07-30 12:07 UTC, anchela commented on src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
> +
unrelated change. can be omitted to simplify reading the diff.

2021-08-04 14:02 UTC, karlpauls commented
Should be covered by #98 now.

2021-08-04 14:02 UTC, closed without merging